services:
  # db:
  #   container_name: db
  #   image: postgres
  #   restart: unless-stopped
  #   env_file: .env
  #   ports:
  #     - 5432:5432
  #   networks: 
  #     - tdc

  django: 
    container_name: django
    image: postgres
    restart: unless-stopped
    env_file: .env
    build: ../srcs/
    volumes:
      - project:/home/
    ports:
      - 8000:8000
    networks: 
      - tdc


volumes:
  project:
    driver: local
    driver_opts:
        type: none
        o: 'bind'
        device: ./scrs


networks:
  tdc:
    name: tdc
    driver: bridge