# Generated by Django 5.1.3 on 2024-11-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='pp',
            field=models.ImageField(upload_to='profile_pic/'),
        ),
    ]
